name: bark-infinity
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - conda-forge::ffmpeg
  - conda-forge::ffmpeg-python
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda
  - huggingface_hub>=0.15
  - boto3
  - funcy
  - numpy
  - scipy
  - tokenizers
  - tqdm
  - transformers
  - pathvalidate
  - rich
  - nltk
  - blas=*=*mkl
  - libblas=*=*mkl
  - faiss-cpu==1.7.0
  - pydub
  - pywin32
  - fairseq
  # sox is for linux, soundfile is for windows
  - sox
  - chardet
  - pip:
    - encodec
    - rich-argparse
    - gradio>=3.34.0
    - audiolm_pytorch
    - universal-startfile
    - ffmpeg-downloader




