name: bark-infinity-nightly
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda>=2.1.0dev
  - huggingface_hub>0.15
  - boto3
  - funcy
  - numpy
  - scipy
  - tokenizers
  - tqdm
  - transformers
  - bandit
  - black
  - codecov
  - flake8
  - hypothesis>=6.14,<7
  - isort>=5.0.0,<6
  - jupyter
  - mypy
  - nbconvert
  - nbformat
  - pydocstyle
  - pylint
  - pytest
  - pytest-cov
  - pysoundfile
  - pathvalidate
  - rich
  - nltk
  - pydub
  