name: bark-infinity
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - huggingface_hub>=0.15
  - boto3
  - funcy
  - numpy
  - scipy
  - tokenizers
  - tqdm
  - transformers
  - bandit
  - black
  - codecov
  - flake8
  - hypothesis>=6.14,<7
  - isort>=5.0.0,<6
  - jupyter
  - mypy
  - nbconvert
  - nbformat
  - pydocstyle
  - pylint
  - pytest
  - pytest-cov
  - pathvalidate
  - rich
  - nltk
  - pydub
  - pywin32
  - pip:
    - encodec
    - rich-argparse
    - gradio
    - audiolm_pytorch
    - universal-startfile
    - ffmpeg-downloader